{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Extensions/MeasuringPointsDataEntry.page",
    "ModalPage": true,
    "ShowActivityIndicator" : false,
    "ActivityIndicatorText" : " "
}
