{
	"_Type": "Action.Type.ODataService.Read",
	"ActionResult": {
		"_Name": "LAMFieldsAction"
	},
	"Target": {
		"Service": "/ZSAPASSETMGRMTADTA_2210/Services/AssetManager.service",
		"EntitySet": "ZGeoInfoSet",
		"QueryOptions": ""
	}
}