{
	"_Type": "Action.Type.CheckRequiredFields",
	"ActionResult": {
		"_Name": "MandatefieldforMDGFL"
	},
	"RequiredFields": [
		"MDGChangerequesttype",
		"PlanningPlant",
		"MP",
		"MainWorkCenter"
	]
}