{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "result"
	},
	"OnFailure": "/SAPAssetManager/Rules/Sync/CheckForSyncErrorsAfterDownloadFailure.js",
	"OnSuccess": "/ZSAPASSETMGRMTADTA_2210/Rules/GetLatitude.js",
	"Service": "/ZSAPASSETMGRMTADTA_2210/Services/ZAssetManager.service",
	"DefiningRequests": [
		{
			"Name": "ZGeoInfoSet",
			"Query": "ZGeoInfoSet",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ZIJC_LOCATIONS",
			"Query": "ZIJC_LOCATIONS",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "ZUserLists",
			"Query": "ZUserLists",
			"AutomaticallyRetrievesStreams": false
		}
	],
	"StoreName": "SAMStore",
	"StoreEncryptionKey": "SAPTest123"
}